### ISSUE TITLE
不能播放rtmp，

### ISSUE THREAD

**Issue by muchuan1988** [tsingsee/EasyPlayer.js#17]
rtmp://58.200.131.2:1935/livetv/hunantv  这个rtmp地址，播放不了，但是vlc可以播放

**Comment by ITsujingli** [comment]
rtmp格式目前还不支持的

**Comment by ITsujingli** [comment]
> rtmp：//58.200.131.2：1935 / livetv / hunantv这个rtmp地址，播放不了，但是vlc可以播放



> rtmp://58.200.131.2:1935/livetv/hunantv 这个rtmp地址，播放不了，但是vlc可以播放

目前还不支持rtmp格式的

**Comment by ITsujingli** [comment]
目前还不支持rtmp格式的
