### ISSUE TITLE
265-Hls 会出现播放非常卡顿的现象

### ISSUE THREAD

**Issue by phoenixZZZ** [tsingsee/EasyPlayer.js#18]
我们用海康的摄像头进行推流，测试发现FLV播放正常，但是HLS播放非常卡顿，看控制台现象似乎一直收不到流；
转换测试工具，使用ffplay进行验证，发现播放正常；
这个问题会是什么情况导致的？

**Comment by ITsujingli** [comment]
265hls如果码率大确实卡
