### ISSUE TITLE
解码方式如何设置为 wasm ？

### ISSUE THREAD

**Issue by bobo0627** [tsingsee/EasyPlayer.js#19]
decodeType  是auto 好像默认 是 mse

**Comment by ITsujingli** [comment]
> encodeType是auto好像默认是mse

播放H.265是自动切换为wasm解码

**Comment by babosa** [comment]
decodeType参数由auto改成soft，表示强制wasm模式解码，这样在手机上就可以用wasm解码播放flv流了

**Comment by ITsujingli** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsingsee/EasyPlayer.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午4:09
收件人:&nbsp;"tsingsee/EasyPlayer.js"<EasyPlayer.js@noreply.github.com&gt;;
抄送:&nbsp;"苏波"<1126080924@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [tsingsee/EasyPlayer.js] 解码方式如何设置为 wasm ？ (#19)





 
decodeType参数由auto改成soft，表示强制wasm模式解码，这样在手机上就可以用wasm解码播放flv流了
