### ISSUE TITLE
H.265 播放报错，Hls 和 http-flv 两种方式都出错

### ISSUE THREAD

**Issue by Alec-DSheng** [tsingsee/EasyPlayer.js#36]
使用Hls方式拉流 报 
Uncaught TypeError: Cannot read property 'segments' of undefined

使用Flv 的方式报 
EasyPlayer-lib.min.js:1 Uncaught Error: Uncaught, unspecified "error" event. (MediaError)
    at n.emit (EasyPlayer-lib.min.js:1)
    at n.<anonymous> (EasyPlayer-lib.min.js:1)
    at n.emit (EasyPlayer-lib.min.js:1)

播放H264的视频流正常

**Comment by Likeadust** [comment]
这边是使用的是这个分支吗？ https://github.com/tsingsee/EasyPlayer.js/tree/legacy

**Comment by Alec-DSheng** [comment]
是这个分支

**Comment by gavin1010** [comment]
要使用EasyWasmPlayer才能播放H265的视频
