### ISSUE TITLE
Legacy分支无法播放H265， EasyPlayer-RTMP客户端可以播放

### ISSUE THREAD

**Issue by mar348** [tsingsee/EasyPlayer.js#47]
你好，
   我用ffmpeg进行RTSP拉流，然后推到nginx-rtmp上， EasyPlayer-RTMP客户端是可以播放的， 但是网页版EasyPlayer.js不能播放， rtmp,flv,m3u8都不能播放， 请帮忙分析下原因，谢谢。 ffmpeg命令如下：
./ffmpeg -i rtsp://admin:root1234@192.168.33.102:554/Streaming/Channels/101  -c:v copy -c:a copy -f flv rtmp://192.168.33.243:51935/live/h265

网页端现象是： 播放rtmp没反应， 播放flv一直pending, 播放m3u8一直显示加载中。。

**Comment by Likeadust** [comment]
Legacy 分支支持H264编码的视频，不支持H265编码的视频。

**Comment by gavin1010** [comment]
EasyWasmPlayer支持H265视频播放
