### ISSUE TITLE
http-flv 无法播放，h265无画面

### ISSUE THREAD

**Issue by godlike10** [tsingsee/EasyPlayer.js#59]
h264的flv流无法播放，使用flvjs可以正常播放。
EasyWasmPlayer.js:21 Uncaught TypeError: Cannot read property 'flvPlayer' of null
    at EasyWasmPlayer.js:21

h265的流有显示码率，控制台也没有任何错误信息，但是黑屏无画面，使用ffmpeg可以播放。

**Comment by godlike10** [comment]
补充下 h265没画面，是我推流的问题，和easyplayerjs无关。

**Comment by godlike10** [comment]
h264是流地址格式的问题，换一种格式就好了

**Comment by meSuperMario** [comment]
你好，h265的问题解决了么，我也同样遇到有码率无画面的问题

**Comment by godlike10** [comment]
你好，我当时的问题是推流导致的。vps/sps/pps 转 flv metadata 的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 上午10:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tsingsee/EasyPlayer.js] http-flv 无法播放，h265无画面 (#59)





 
你好，h265的问题解决了么，我也同样遇到有码率无画面的问题

**Comment by meSuperMario** [comment]
谢谢，我的估计也是推流问题，我的是使用rtsp转hls，再去找找什么原因，感谢。

**Comment by Glorysun** [comment]
> 谢谢，我的估计也是推流问题，我的是使用rtsp转hls，再去找找什么原因，感谢。

请问问题解决了吗，我是用zlm拉海康H265的rtsp流转的hls，用vlc可以播放，但是用easyPlayer有码率但是没有画面，和libDecoder.wasm 404有关系吗
![1616553645(1)](https://user-images.githubusercontent.com/56619202/112246316-69e7ac00-8c8d-11eb-8328-6ecacee99107.jpg)
