### ISSUE TITLE
如何播放萤石云平台的HLS直播流

### ISSUE THREAD

**Issue by lenghuo** [tsingsee/EasyPlayer.js#62]
从萤石云获取m3u8的直播地址后，按照文档编写代码，发现提示错误，有时是ts文件的跨域错误，还有一个是 Cannot read property 'samples' of undefined ，不知怎么回事？是萤石云不被支持吗？还是？？

**Comment by popdzytz** [comment]
萤石云可以用萤石云的插件播放，并使用萤石云提供的.live地址，可做到稳定无延迟。

**Comment by lenghuo** [comment]
> 萤石云可以用萤石云的插件播放，并使用萤石云提供的.live地址，可做到稳定低延迟。

是的，但是萤石云的插件占用内存和CPU太高……
