### ISSUE TITLE
http-flv 播放提示 Unsupport url

### ISSUE THREAD

**Issue by zypy333** [tsingsee/EasyPlayer.js#64]
在vlc里正常播放,url格式有什么要求吗,是不是必须是.flv结尾

**Comment by CuiXu1987** [comment]
不是必须是.flv结尾
提供一下你的console消息，或者发一下你的url我试试

**Comment by zypy333** [comment]
console提示就是Unsupport url,没截图,用nginx-flv转推的,把stream改成.flv结尾就能播了,局域网网url没法发布
