### ISSUE TITLE
播放错误处理？ 支持隐藏控制条吗？

### ISSUE THREAD

**Issue by huangzhengyon** [tsingsee/EasyPlayer.js#65]
![image](https://user-images.githubusercontent.com/23194762/112080986-e27f3780-8bbd-11eb-9811-dbae1480f65f.png)
![image](https://user-images.githubusercontent.com/23194762/112081021-f3c84400-8bbd-11eb-853a-2667cc05a2d6.png)
会这样一直报错， 虽然我用ff播放器也播放不了，但是也不能这样一直循环报错啊。 还有就是怎么才能隐藏控制条，不让用户点击播放和停止按钮呢？

**Comment by CuiXu1987** [comment]
音频编码格式只能是AAC或MP3。
控制条隐藏不了

**Comment by huangzhengyon** [comment]
那是否可以优化一下这个错误信息，不要无限循环报错，提示用户播放错误呢

**Comment by CuiXu1987** [comment]
你用的音频编码格式是什么，可以将视频文件发给我测试一下么，410053416@qq.com

**Comment by huangzhengyon** [comment]
我这边是拿的实时视频，上面说的这个错误提示就是在拉流失败的情况下发生的(状态码401)

**Comment by CuiXu1987** [comment]
已修复，不支持的音频格式，只会报错一次
请使用master分支最新代码，测试一下

**Comment by huangzhengyon** [comment]
破费特
