### ISSUE TITLE
TP link H265 HLS直播流黑屏无法播放

### ISSUE THREAD

**Issue by SchumyHao** [tsingsee/EasyPlayer.js#66]
测试URL： https://live-hls-ipc.tplinkcloud.com.cn:8100/store/b9ee392dde6adcbd/1/5b2d577e/playlist.m3u8?uuid=5b2d577e

视频流无法播放，速率一直在变化，图像一致黑色
![image](https://user-images.githubusercontent.com/4982108/112346235-ba4c2180-8d00-11eb-9286-4c8e161c33cc.png)
![image](https://user-images.githubusercontent.com/4982108/112346277-c2a45c80-8d00-11eb-9df2-899777d90ee3.png)
![image](https://user-images.githubusercontent.com/4982108/112346394-dea7fe00-8d00-11eb-97ef-4bf019c6fdb5.png)
![image](https://user-images.githubusercontent.com/4982108/112346426-e8c9fc80-8d00-11eb-8dd4-04174ecb4548.png)

**Comment by CuiXu1987** [comment]
hi，这个url是有效的么，我用VLC也无法播放

**Comment by SchumyHao** [comment]
昨天设备掉线，流断开了。  现在已经恢复。您可以再测试一下

**Comment by SchumyHao** [comment]
@atlas1119

**Comment by CuiXu1987** [comment]
已修复，请使用master分支最新代码，测试一下

**Comment by SchumyHao** [comment]
<img width="1415" alt="Screen Shot 2021-03-26 at 2 42 04 PM" src="https://user-images.githubusercontent.com/4982108/112592772-7ad91e80-8e41-11eb-9472-c458a79e83f4.png">

您好。
感谢您快速回复。
刚刚同步最新master分支代码后， 有一个报错，视频依然无法加载。
请您再看一下

**Comment by CuiXu1987** [comment]
是这个地址么，https://live-hls-ipc.tplinkcloud.com.cn:8100/store/b9ee392dde6adcbd/1/5b2d577e/playlist.m3u8?uuid=5b2d577e
我这里用Chrome是可以的
![image](https://user-images.githubusercontent.com/19907031/112608828-bf6eb500-8e55-11eb-944e-f02f389a6b1b.png)

**Comment by SchumyHao** [comment]
好的， 感谢大佬支持！
