### ISSUE TITLE
按照官方的npm引入写的代码，报错，3fd7aed2-ce65-4c4b-9826-06a4adcbd5f9:1 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0) at Error

### ISSUE THREAD

**Issue by keke195** [tsingsee/EasyPlayer.js#98]
![image](https://user-images.githubusercontent.com/19198738/121135933-9d3adf80-c867-11eb-9740-58bc602468b5.png)

**Comment by sjxhgjxf** [comment]
兄嘚，我今天用也刚遇到。

**Comment by keke195** [comment]
问题解决了，我之前使用的vuecli2的，换成vuecli3的然后在index.html同级目录放入libDecoder.wasm文件就可以了（查了百度说是libDecoder.wasm文件没有被加载成功，必须要把文件放到WEB服务器的root根目录下，只有在该目录下才能被调用起来，这是使用libDecoder.wasm文件的强制规定。）

**Comment by sjxhgjxf** [comment]
对的。我本地也是vuecli2导致的该报错，打包后部署到服务器并将libDecoder.wasm放在服务根目录就不再报错了。

**Comment by sjxhgjxf** [comment]
![image](https://user-images.githubusercontent.com/8445821/121478014-1d457e80-c9fb-11eb-9a5e-de60cb26fcbd.png)
报错解决了，但是播放h265无画面，一直卡在loading画面，且控制台有：
SetInterval: 152
Update interval: 152
SetInterval: 80
信息输出，你有遇到过吗？

**Comment by keke195** [comment]
我没有这个问题，没遇到过哦

**Comment by sjxhgjxf** [comment]
你也是用来播放的h265格式吗

**Comment by keke195** [comment]
是h265的

**Comment by sjxhgjxf** [comment]
![image](https://user-images.githubusercontent.com/8445821/121479018-326edd00-c9fc-11eb-947c-6013cfb07e7d.png)
h265 ts加载后通过preview是这样的，这算乱码吗？

**Comment by sjxhgjxf** [comment]
另外vuecli2本地run的话有什么好的思路解决Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0) 报错吗？

**Comment by keke195** [comment]
我没有这个，我的h265是http-flv的，vuecli2我没解决，直接项目升级到了vuecli3了

**Comment by sjxhgjxf** [comment]
好的，多谢 h265 http-flv的估计播放确实没问题。  能帮忙看下你的h265 htt-flv
返回的响应头Content-Type吗，我的h265返回的是Content-Type: video/mp2t 我怀疑是这个原因导致的播放不了。
![image](https://user-images.githubusercontent.com/8445821/121479742-ec664900-c9fc-11eb-8f72-e9c73761d8a4.png)

**Comment by keke195** [comment]
video/x-flv

**Comment by sjxhgjxf** [comment]
兄弟你是参考的分支master/demo实现的还是分支H265-Player/demo实现的？

**Comment by keke195** [comment]
master/demo

**Comment by sjxhgjxf** [comment]
好的
